language: ruby
rvm: 2.4.1
cache:
  - bundler
before_script:
  - rake db:create
  - rake db:migrate
deploy:
  api_key:
    secure: gQ2BGkir1W0cUOHuYuq/yZRfKhnd1afStpfqWuEj5610fXLetdhK7btAl8aHp6GIq5uuJh044RM2OTlszt3hoWm1iMMBkWFANVQ+g2paR2vsIFJWqU9BLNub5TV/F8p1K09YdgmmeypXpi34RsM87LicMBY8dbUlHXbXBFXAe5VO8aoF1E/hBgSGG4y3ubciwft5APNJowZsa/n/jr76x+8ex5rnXVUTgWQ0QTg6Py9MFYJh11EjhKgVKpEa1/2irZ1RAzIXT8HQOv5JFGE0Gvc6wKguW7kH5WShQyw3s9aBq22SRWKYwSpCPPEkC9igRgnkwDbf84vFzD/+u/c2TNE2vrQ/vXSfUjD0iQJaHmOeVh6Ey0I/5RIeCYHRmyaeCimkUk0Y+V3sCBFrnEJNDE0UbOIOtEJstxcd1AFFpqD9RguYMJCgb9Um3EWRQ+PlMJc2yxMyZSMfxKTSrac4hGosUJtQOdIQXwScbwWuB2miTGPcLdU04EEKoAEYTXkkJ3oolpFovISGqvRN9EZv4woPWoygX5EqaAmANsa+kIUyi40UrUMptEWvXhsxqHY6wh8nw2zdeZIJ+5YQFGbrEUwybQtGWgZ8S1jibJ9FVSIPePXyGlbGq4ry5jcySL2gEevHO3lJUi64D301ezJ4ZVwbXK2Kf0n60YzfZmyZlkw=
